#Canonical cellmarkers

cellmarker.lymph<-c("CD3D","CD3E","CD3G","TRAC")
cellmarker.immune<-c("CD4","LCK","CD28")
cellmarker.cd8<-c("CD8A","CD8B","PRF1","GZMB")
cellmarker.bcell<-c("CD19","CD20","MS4A1","IGHM")
cellmarker.macro<-c("CD14","FCGR3A","KLRF1")
cellmarker.hspc<-c("CD34", "FLT3", "KIT")
cellmarker.dc<-c("CD80","CD86","IRF8")
cellmarker.dnT<-c("TOX")
cellmarker.gdT<-c("IL17A", "IL17F","IL22")
cellmarker.eryt<-c("HBB","HBA","EPOR","KLF1")
cellmarker.platelet<-c("GP9","PF4","TSP1","VWF")
cellmarker.platelet2<-c("ITGA2B","ITGB3","GP1BA","GP1BB")
cellmarker.Tfh<-c("PDCD1","TIGIT", "CCR7","TCF7")
cellmarker.TregActive<-c("FOXP3","IL2RA","BIRC5","MKI67")
cellmarker.Th17cytoly<-c("CCR6","RORA","NKG7","EOMES")
cellmarker.EffectorActive<-c("ANXA1","S100A10","CCL5","CXCR3")
cellmarker.Cytotoxic1<-c("PRF1", "GZMB","GZMA", "GZMK")
cellmarker.Cytotoxic2<-c("TBX21","PRDM1","SERPINB9","IFNG")
cellmarker.survival<-c("TNFRSF4", "BCL2L1","BCL2A1", "BCL2")
cellmarker.TCM<-c("IL7R","LEF1","CD62L","ITGAE")
cellmarker.TRM<-c("ZEB2","KLRB1","TCF1","S1PR1")
cellmarker.activated<-c("CD69","IL2RA","PTPRC","IL2")
cellmarker.activated2<-c("IL4","IL17A","TCF1","S1PR1")
cellmarker.proliferating<-c("BIRC5","TOP2A","MCM2","PCNA")
cellmarker.Treg<-c("FOXP3","TNFRSF18","CTLA4","IKZF2")
cellmarker.Th1andTfh<-c("IL12RB2","IRF1","BCL6","CCR6")
cellmarker.Tfh2<-c("CXCR5","ICOS","PD1","IL21")
cellmarker.granzyme<-c("GZMA", "GZMB","GZMK","PRF1","SERPINB9", "BCL2","TNFRSF4")
cellmarker.survival2<-c("BCL2L1","BCL2A1","CD74","CCL5","BIRC5","LYAR","DUSP2")
